apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-api
  template:
    metadata:
      labels:
        app: iris-api
    spec:
      containers:
      - name: iris-api
        image: iris-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: iris-service
spec:
  selector:
    app: iris-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
